"""BNCH-02 + BNCH-03 coverage: the JSON->README renderer and the plot scripts.

These tests close the bench-protocol round-trip (rule 17): every headline number
in the README is regenerated by benchmarks/report.py from a committed
benchmarks/results/*.json file, never hand-typed, so the doc and the JSON cannot
drift. They also enforce rule 16 (the loss rows must be present), the exact
DESIGN_SYSTEM series colors (rule 19), the headless Agg plot path, and the hard
hygiene rule (the published README references no agent-infra path).

json.load only (Security V5): a results file is data, never code; these tests and
the modules under test never eval or pickle one.
"""

from __future__ import annotations

import ast
import json
import os
import sys

import pytest

# No test imports a benchmarks module by default. Mirror the inverse sys.path
# insert bench_matmul.py does to reach tests/ (its lines 39-42), pointing at
# benchmarks/ instead, then import the renderer and the plot script under test.
_BENCH_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "benchmarks"
)
if _BENCH_DIR not in sys.path:
    sys.path.insert(0, _BENCH_DIR)

import report  # noqa: E402

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_README = os.path.join(_REPO_ROOT, "README.md")

# Agent-infrastructure path fragments that must never appear in a tracked public
# artifact. The README hygiene rule is hard: restate reasoning inline, never
# point a reader at the planning or agent directories.
_INFRA_TOKENS = (".agent", ".planning", ".claude", "CLAUDE.md")


def _read_text(path: str) -> str:
    with open(path, encoding="utf-8") as handle:
        return handle.read()


def readme_hygiene(text: str) -> list:
    """Return the agent-infra tokens found in text (empty list means clean).

    The helper the README hygiene test asserts on: it scans a text blob for any
    .agent / .planning / .claude / CLAUDE.md reference and returns every hit, so
    a published artifact leaks no internal path (rule: no tracked file references
    agent infrastructure).
    """
    return [token for token in _INFRA_TOKENS if token in text]


# --- Task 1: the JSON->README renderer (BNCH-03, rules 16 + 17). ---


def test_report_render_loss_rows():
    # rule 16: the rendered report MUST carry the loss regimes. A results section
    # with no loss row on this hardware is the protocol red flag, because f64
    # mid-size parity is the stated target, not a win. Assert all three loss
    # framings are present: CPU-02 (does not beat OpenBLAS), CPU-06 (loses to
    # NumPy small), CPU-05 (below the 4x scaling the cores would give).
    report_text = report.render_report()
    lowered = report_text.lower()
    assert "openblas" in lowered  # CPU-02 f64 parity framing names the baseline
    assert "does not beat openblas" in lowered  # CPU-02 stated as not-a-win
    assert "loses to numpy" in lowered  # CPU-06 small-matrix loss outcome
    assert "below the 4x" in lowered  # CPU-05 sub-4x scaling framing


def test_report_render_round_trip():
    # rule 17: every headline number the report emits equals a json.load-ed
    # value, not a literal in report.py. Load each committed JSON here
    # independently and assert the rendered string contains the value computed
    # from it, so a number that drifted from its source fails.
    report_text = report.render_report()

    # CPU-02 floor 0.79 from cpu02_analysis.high_effort_best_floor.n2048.ratio
    # (the high-effort best floor, NOT the lower cases floor 0.678).
    cpu02 = json.load(
        open(os.path.join(report.RESULTS_DIR, "cpu02_f64_zpicy.json"))
    )
    best = cpu02["cpu02_analysis"]["high_effort_best_floor"]["n2048"]["ratio"]
    assert f"{best:.2f}" in report_text
    assert best == 0.79  # the documented CPU-02 high-effort best floor

    # CPU-05 2.87x from tuning/scaling_zpicy.json ratio_6_vs_1_floor.
    scaling = json.load(
        open(os.path.join(report.RESULTS_DIR, "tuning", "scaling_zpicy.json"))
    )
    ratio = scaling["ratio_6_vs_1_floor"]
    assert f"{ratio:.2f}" in report_text

    # CPU-06 small-matrix losses from cpu06_f32_zpicy.json cases speedup_vs_numpy.
    cpu06 = json.load(
        open(os.path.join(report.RESULTS_DIR, "cpu06_f32_zpicy.json"))
    )
    for case in cpu06["cases"]:
        assert f"{case['speedup_vs_numpy']:.2f}" in report_text

    # FUSE-05 CPU 3.236 and GPU 71.37 from the fused JSON.
    fuse_cpu = json.load(
        open(os.path.join(report.RESULTS_DIR, "fuse05_cpu_f32_zpicy.json"))
    )
    fuse_gpu = json.load(
        open(os.path.join(report.RESULTS_DIR, "fuse05_gpu_f32_zpicy.json"))
    )
    assert f"{fuse_cpu['cpu_cases'][0]['speedup_floor']:.2f}" in report_text
    assert (
        f"{fuse_gpu['gpu_cases'][0]['ratio_vs_numpy_cpu_f32']:.2f}"
        in report_text
    )


def test_report_gpu08_reads_committed_matrix():
    # The GPU-08 headline reads the COMMITTED results/zpicy_gpu_matrix.json (the
    # 07-02 without-transfer warm series), NOT results/local/zpicy_gpu08.json
    # (gitignored, absent on a fresh clone). The committed matrix yields ~23.5x
    # at n=2048; 22.83 is the documented cross-check value the same device-
    # resident GPU-08 measurement produced, so assert the rendered ratio sits in
    # the cross-check band (22.0-24.5) and is read from the file, not a literal.
    matrix = json.load(
        open(os.path.join(report.RESULTS_DIR, "zpicy_gpu_matrix.json"))
    )
    rendered_ratio = report._gpu08_ratio(matrix)
    warm = [
        c
        for c in matrix["gpu_cases"]
        if c["label"] == "without-transfer" and c["phase"] == "warm"
    ]
    largest = max(warm, key=lambda c: c["n"])
    assert rendered_ratio == largest["ratio_vs_numpy_cpu_f32"]
    # The cross-check: the committed device-resident GPU-08 ratio is in the
    # documented ~22.83 band (the local file recorded 22.83 at the same size).
    assert 22.0 <= rendered_ratio <= 24.5
    # And the rendered table carries the figure (round-trip, not a literal).
    assert f"{rendered_ratio:.2f}" in report.render_report()

    # The committed matrix is the source; the gitignored results/local/ scratch
    # is NOT read. RESULTS_DIR resolves to the committed results/ directory (it
    # survives a fresh clone), and no render path opens a results/local/ file.
    assert os.path.basename(report.RESULTS_DIR) == "results"
    # No string LITERAL in report.py code names the gitignored local scratch:
    # parse the AST and scan only string constants (docstrings and comments are
    # prose that documents the contract and are excluded). A render that read
    # results/local/zpicy_gpu08.json would orphan the number on a clone.
    source = _read_text(os.path.join(_BENCH_DIR, "report.py"))
    tree = ast.parse(source)
    docstrings = {
        ast.get_docstring(node, clean=False)
        for node in ast.walk(tree)
        if isinstance(
            node, (ast.Module, ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)
        )
    }
    literals = [
        node.value
        for node in ast.walk(tree)
        if isinstance(node, ast.Constant)
        and isinstance(node.value, str)
        and node.value not in docstrings
    ]
    assert all("local" not in lit for lit in literals)


def test_report_no_literal_headline_numbers():
    # rule 17 enforced structurally: report.py contains none of the headline
    # numbers as source literals. Every number is read from JSON; a literal would
    # be a hand-copied number that can drift. Scan the source for the exact
    # headline tokens.
    source = _read_text(os.path.join(_BENCH_DIR, "report.py"))
    forbidden = ["0.79", "2.87", "3.236", "3.24", "71.37", "71.4", "22.83", "23.54"]
    for token in forbidden:
        assert token not in source, f"headline literal {token} in report.py"


def test_load_series_rejects_unverified(tmp_path):
    # load_series enforces rule 9 (manifest present) and rule 11 (every case
    # verified=true). A verified-false or manifest-less file is rejected before
    # any render. json.load only: the validator never evals or pickles.
    good = tmp_path / "good.json"
    good.write_text(
        json.dumps(
            {"manifest": {"blas": "x"}, "cases": [{"n": 8, "verified": True}]}
        )
    )
    assert report.load_series(str(good))["manifest"]["blas"] == "x"

    no_manifest = tmp_path / "no_manifest.json"
    no_manifest.write_text(json.dumps({"cases": [{"n": 8, "verified": True}]}))
    with pytest.raises(AssertionError):
        report.load_series(str(no_manifest))

    unverified = tmp_path / "unverified.json"
    unverified.write_text(
        json.dumps({"manifest": {}, "cases": [{"n": 8, "verified": False}]})
    )
    with pytest.raises(AssertionError):
        report.load_series(str(unverified))

    # A high_cv+verified case PASSES unchanged: the noise flag never strips a
    # verified series (the CPU sweeps this consumes are high_cv every run).
    noisy = tmp_path / "noisy.json"
    noisy.write_text(
        json.dumps(
            {
                "manifest": {},
                "gpu_cases": [{"n": 256, "verified": True, "high_cv": True}],
            }
        )
    )
    assert report.load_series(str(noisy)) is not None


def test_report_schema_branches():
    # The renderer handles all four committed shapes with no KeyError: matmul
    # (cases + analysis), gpu (gpu_cases + with_transfer_cases), fused
    # (cpu_cases / gpu_cases), and scaling (series + ratio). render_report walks
    # every one, so a clean call proves the branch coverage.
    text = report.render_report()
    assert "float64 matmul" in text
    assert "GPU matmul" in text
    assert "Fused 3-op chain" in text
    assert "Thread scaling" in text
    assert "Hardware" in text


def test_report_blocking_cites_saved_winner():
    # PITFALL 5: the blocking note cites the SAVED sweep winner (mc=48 on this
    # machine), never the hand-picked MC=96 from a doc. Assert the rendered note
    # carries the JSON winner, read from the file.
    sweep = json.load(
        open(os.path.join(report.RESULTS_DIR, "tuning", "sweep_zpicy.json"))
    )
    note = report.render_blocking_note(sweep)
    assert f"mc={sweep['winner']['mc']}" in note
    assert sweep["winner"]["mc"] == 48  # the saved winner, not 96
