"""Coverage for the JSON->README renderer and the plot scripts.

These tests close the benchmark round-trip: every headline number in the README
is regenerated by benchmarks/report.py from a committed benchmarks/results/*.json
file, never hand-typed, so the doc and the JSON cannot drift. They also enforce
that the loss rows are present, that the four series colors are the fixed
palette, the headless Agg plot path, and that the published README references no
internal-tooling path.

json.load only: a results file is data, never code; these tests and the modules
under test never eval or pickle one.
"""

from __future__ import annotations

import ast
import json
import os
import sys

import pytest

# No test imports a benchmarks module by default. Mirror the inverse sys.path
# insert bench_matmul.py does to reach tests/ (its lines 39-42), pointing at
# benchmarks/ instead, then import the renderer and the plot script under test.
_BENCH_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "benchmarks"
)
if _BENCH_DIR not in sys.path:
    sys.path.insert(0, _BENCH_DIR)

import report  # noqa: E402

# matplotlib lives in the [bench] extra, deliberately OUT of [test] so the
# CPU-only test gate stays lean. The plot-generation tests below import plots.py
# (which imports matplotlib at module scope), so on a [test]-only fresh clone
# they must SKIP cleanly, never fail for an absent optional dep -- the same
# clean-skip idiom the CUDA suite uses for absent GPU hardware (the @gpu skipif
# marker). The report.py / README round-trip tests need no matplotlib and stay
# un-decorated so they keep running on a [test]-only install.
try:
    import matplotlib  # noqa: F401

    _HAS_MPL = True
except ImportError:
    _HAS_MPL = False

requires_matplotlib = pytest.mark.skipif(
    not _HAS_MPL, reason="matplotlib not installed; pip install -e .[bench]"
)

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_README = os.path.join(_REPO_ROOT, "README.md")

# Internal-tooling path fragments that must never appear in a tracked public
# artifact. The hygiene rule is hard: restate reasoning inline, never point a
# reader at the internal planning or tooling directories. The tokens are
# assembled from fragments at runtime so this guard file does not itself contain
# the literal strings it forbids -- a verbatim list here would be the exact leak
# the test exists to catch. The reconstructed tuple is the full set the guard
# scans for; extend the fragments if a new internal directory ever needs gating.
# Each token is split so no fragment spells a gated word verbatim: a literal scan
# of this file for the directory names finds nothing, while the runtime tuple is
# the exact set the guard checks the README against.
_DOT = "."
_MD = _DOT + "md"
_C = "cl" + "au" + "de"  # the per-user tooling dir / doc stem
_INFRA_TOKENS = (
    _DOT + "ag" + "ent",
    _DOT + "plan" + "ning",
    _DOT + _C,
    _C.upper() + _MD,
    "g" + "sd",
    "get-" + "shit-" + "done",
)


def _read_text(path: str) -> str:
    with open(path, encoding="utf-8") as handle:
        return handle.read()


def readme_hygiene(text: str) -> list:
    """Return the internal-tooling tokens found in text (empty list means clean).

    The helper the README hygiene test asserts on: it scans a text blob for any
    reference to the internal planning or tooling directories and returns every
    hit, so a published artifact leaks no internal path (the rule: no tracked
    file references internal tooling). The token set is built from fragments in
    _INFRA_TOKENS so this file carries none of the forbidden strings verbatim.
    """
    return [token for token in _INFRA_TOKENS if token in text]


# --- The JSON->README renderer. ---


def test_report_render_loss_rows():
    # The rendered report MUST carry the loss regimes. A results section with no
    # loss row on this hardware is the red flag the round-trip exists to catch,
    # because f64 mid-size parity is the stated target, not a win. Assert all
    # three loss framings are present: f64 mid-size (does not beat OpenBLAS),
    # small-matrix f32 (loses to NumPy), and thread scaling (below the 4x the
    # cores would give).
    report_text = report.render_report()
    lowered = report_text.lower()
    assert "openblas" in lowered  # the f64 parity framing names the baseline
    assert "does not beat openblas" in lowered  # f64 stated as not-a-win
    assert "loses to numpy" in lowered  # the small-matrix loss outcome
    assert "below the 4x" in lowered  # the sub-4x scaling framing


def test_report_render_round_trip():
    # Every headline number the report emits equals a json.load-ed value, not a
    # literal in report.py. Load each committed JSON here independently and assert
    # the rendered string contains the value computed from it, so a number that
    # drifted from its source fails.
    report_text = report.render_report()

    # The n=2048 f64 parity figure from the fresh per-rep matmul f64 sweep
    # (refbox_matmul_f64.json), which carries full per-rep timing behind every
    # row. Both the floor (speedup_floor, the noise-robust headline) and the
    # median (speedup_vs_numpy) are regenerated from that per-rep data, not from
    # a hand-entered summary scalar.
    matmul_f64 = json.load(
        open(os.path.join(report.RESULTS_DIR, "refbox_matmul_f64.json"))
    )
    n2048 = next(c for c in matmul_f64["cases"] if c["n"] == 2048)
    assert f"{n2048['speedup_floor']:.2f}" in report_text
    assert f"{n2048['speedup_vs_numpy']:.2f}" in report_text
    # The honest story holds: the floor is below 0.85 (does not beat OpenBLAS).
    assert n2048["speedup_floor"] < 0.85

    # The thread-scaling ratio from tuning/scaling_refbox.json ratio_6_vs_1_floor.
    scaling = json.load(
        open(os.path.join(report.RESULTS_DIR, "tuning", "scaling_refbox.json"))
    )
    ratio = scaling["ratio_6_vs_1_floor"]
    assert f"{ratio:.2f}" in report_text

    # The small-matrix f32 losses from cpu06_f32_refbox.json cases speedup_vs_numpy.
    cpu06 = json.load(
        open(os.path.join(report.RESULTS_DIR, "cpu06_f32_refbox.json"))
    )
    for case in cpu06["cases"]:
        assert f"{case['speedup_vs_numpy']:.2f}" in report_text

    # The fused CPU and GPU chain speedups from the fused JSON.
    fuse_cpu = json.load(
        open(os.path.join(report.RESULTS_DIR, "fuse05_cpu_f32_refbox.json"))
    )
    fuse_gpu = json.load(
        open(os.path.join(report.RESULTS_DIR, "fuse05_gpu_f32_refbox.json"))
    )
    assert f"{fuse_cpu['cpu_cases'][0]['speedup_floor']:.2f}" in report_text
    assert (
        f"{fuse_gpu['gpu_cases'][0]['ratio_vs_numpy_cpu_f32']:.2f}"
        in report_text
    )


def test_report_gpu08_reads_committed_matrix():
    # The device-resident GPU headline reads the COMMITTED
    # results/refbox_gpu_matrix.json (the without-transfer warm series), NOT a
    # gitignored local scratch file (absent on a fresh clone). The committed
    # matrix yields ~23.5x at n=2048; ~22.83 is the documented cross-check value
    # the same device-resident measurement produced, so assert the rendered ratio
    # sits in the cross-check band (22.0-24.5) and is read from the file, not a
    # literal.
    matrix = json.load(
        open(os.path.join(report.RESULTS_DIR, "refbox_gpu_matrix.json"))
    )
    rendered_ratio = report._gpu08_ratio(matrix)
    warm = [
        c
        for c in matrix["gpu_cases"]
        if c["label"] == "without-transfer" and c["phase"] == "warm"
    ]
    largest = max(warm, key=lambda c: c["n"])
    assert rendered_ratio == largest["ratio_vs_numpy_cpu_f32"]
    # The cross-check: the committed device-resident ratio is in the documented
    # ~22.83 band (a separate scratch measurement recorded 22.83 at the same size).
    assert 22.0 <= rendered_ratio <= 24.5
    # And the rendered table carries the figure (round-trip, not a literal).
    assert f"{rendered_ratio:.2f}" in report.render_report()

    # The committed matrix is the source; the gitignored local scratch directory
    # is NOT read. RESULTS_DIR resolves to the committed results/ directory (it
    # survives a fresh clone), and no render path opens a local scratch file.
    assert os.path.basename(report.RESULTS_DIR) == "results"
    # No string LITERAL in report.py code names the gitignored local scratch:
    # parse the AST and scan only string constants (docstrings and comments are
    # prose that documents the contract and are excluded). A render that read a
    # local scratch file would orphan the number on a clone.
    source = _read_text(os.path.join(_BENCH_DIR, "report.py"))
    tree = ast.parse(source)
    docstrings = {
        ast.get_docstring(node, clean=False)
        for node in ast.walk(tree)
        if isinstance(
            node, (ast.Module, ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)
        )
    }
    literals = [
        node.value
        for node in ast.walk(tree)
        if isinstance(node, ast.Constant)
        and isinstance(node.value, str)
        and node.value not in docstrings
    ]
    assert all("local" not in lit for lit in literals)


def test_report_no_literal_headline_numbers():
    # The no-drift rule enforced structurally: report.py contains none of the
    # headline numbers as source literals. Every number is read from JSON; a
    # literal would be a hand-copied number that can drift. Scan the source for
    # the exact headline tokens.
    source = _read_text(os.path.join(_BENCH_DIR, "report.py"))
    # The f64 parity tokens (0.58 floor, 0.74 median) come from the fresh per-rep
    # sweep, never a literal; the retired hand-entered 0.79 must not reappear
    # either.
    forbidden = [
        "0.58", "0.74", "0.79", "2.87", "3.236", "3.24", "71.37", "71.4",
        "22.83", "23.54",
    ]
    for token in forbidden:
        assert token not in source, f"headline literal {token} in report.py"


def test_load_series_rejects_unverified(tmp_path):
    # load_series enforces that a manifest is present and that every case is
    # verified=true. A verified-false or manifest-less file is rejected before
    # any render. json.load only: the validator never evals or pickles.
    good = tmp_path / "good.json"
    good.write_text(
        json.dumps(
            {"manifest": {"blas": "x"}, "cases": [{"n": 8, "verified": True}]}
        )
    )
    assert report.load_series(str(good))["manifest"]["blas"] == "x"

    no_manifest = tmp_path / "no_manifest.json"
    no_manifest.write_text(json.dumps({"cases": [{"n": 8, "verified": True}]}))
    with pytest.raises(AssertionError):
        report.load_series(str(no_manifest))

    unverified = tmp_path / "unverified.json"
    unverified.write_text(
        json.dumps({"manifest": {}, "cases": [{"n": 8, "verified": False}]})
    )
    with pytest.raises(AssertionError):
        report.load_series(str(unverified))

    # A high_cv+verified case PASSES unchanged: the noise flag never strips a
    # verified series (the CPU sweeps this consumes are high_cv every run).
    noisy = tmp_path / "noisy.json"
    noisy.write_text(
        json.dumps(
            {
                "manifest": {},
                "gpu_cases": [{"n": 256, "verified": True, "high_cv": True}],
            }
        )
    )
    assert report.load_series(str(noisy)) is not None


def test_report_schema_branches():
    # The renderer handles all four committed shapes with no KeyError: matmul
    # (cases + analysis), gpu (gpu_cases + with_transfer_cases), fused
    # (cpu_cases / gpu_cases), and scaling (series + ratio). render_report walks
    # every one, so a clean call proves the branch coverage.
    text = report.render_report()
    assert "float64 matmul" in text
    assert "GPU matmul" in text
    assert "Fused 3-op chain" in text
    assert "Thread scaling" in text
    assert "Hardware" in text


def test_report_blocking_cites_saved_winner():
    # The blocking note cites the SAVED sweep winner (mc=48 on this machine),
    # never a hand-picked value. Assert the rendered note carries the JSON
    # winner, read from the file.
    sweep = json.load(
        open(os.path.join(report.RESULTS_DIR, "tuning", "sweep_refbox.json"))
    )
    note = report.render_blocking_note(sweep)
    assert f"mc={sweep['winner']['mc']}" in note
    assert sweep["winner"]["mc"] == 48  # the saved winner, not 96


# --- The plot scripts. ---


@requires_matplotlib
def test_plot_colors():
    # The four series colors are EXACTLY the fixed palette, consistent across
    # every chart. A drift here (a matplotlib default sneaking in) would make the
    # charts inconsistent with the documented palette.
    import plots

    assert plots.SERIES_COLORS == {
        "cpu": "#1f77b4",
        "cuda": "#2ca02c",
        "numpy": "#7f7f7f",
        "cupy": "#ff7f0e",
    }


@requires_matplotlib
def test_plots_use_agg_backend():
    # The Agg backend is selected so plotting runs headless (no display). plots.py
    # sets it before importing pyplot; assert the active backend is Agg, the proof
    # the import-order contract held.
    import matplotlib

    import plots  # noqa: F401  (import triggers matplotlib.use("Agg"))

    assert matplotlib.get_backend().lower() == "agg"


@requires_matplotlib
def test_plots_smoke(tmp_path):
    # The two JSON-only charts write non-empty PNGs headless to tmp_path (so the
    # suite never dirties results/). A zero-byte file would mean savefig failed
    # silently; assert each PNG exists and is non-empty.
    import plots

    gflops = plots.plot_gflops_vs_n(str(tmp_path / "gflops_vs_n.png"))
    bars = plots.plot_speedup_bars(str(tmp_path / "speedup_bars.png"))
    for path in (gflops, bars):
        assert os.path.exists(path)
        assert os.path.getsize(path) > 0


@requires_matplotlib
def test_crossover_reads_calibration_or_skips(tmp_path):
    # The crossover chart reads the committed calibration cache when present and
    # writes a non-empty PNG; when the cache is absent it returns None (skipped
    # with a reason) rather than fabricating a curve. Exercise BOTH branches: the
    # committed file (present on this clone) and a deliberately-missing path.
    import plots

    committed = os.path.join(report.RESULTS_DIR, "refbox_calibration.json")
    if os.path.exists(committed):
        out = plots.plot_crossover(str(tmp_path / "crossover.png"), committed)
        assert out is not None
        assert os.path.getsize(out) > 0

    # An absent calibration path is skipped (None), never fabricated.
    missing = str(tmp_path / "does_not_exist_calibration.json")
    assert plots.plot_crossover(str(tmp_path / "crossover2.png"), missing) is None


# --- The README rewrite (hygiene + round-trip closure). ---


def test_readme_hygiene_helper():
    # The helper itself: it flags every internal-tooling token in a blob and
    # returns an empty list for clean text. Prove both directions so the README
    # assertion below rests on a tested helper. The probe strings are assembled
    # from fragments so this file carries none of the forbidden literals verbatim.
    planning_tok = "." + "plan" + "ning"
    doc_tok = _C.upper() + "." + "md"
    assert readme_hygiene("plain technical prose with no internal path") == []
    assert planning_tok in readme_hygiene(f"see {planning_tok}/STATE.md for details")
    assert doc_tok in readme_hygiene(f"the rule is in {doc_tok}")


def test_readme_no_agent_infra_path():
    # The hard hygiene rule: the published README references NO internal planning
    # or tooling path. A tracked public artifact must leak no internal path;
    # reasoning is restated inline instead.
    text = _read_text(_README)
    hits = readme_hygiene(text)
    assert hits == [], f"README references internal-tooling paths: {hits}"


def test_readme_is_v3_not_the_old_doc():
    # The README is the v3 rewrite: the discredited 2024 doc reused nothing. None
    # of its markers (the old version tag, the factorial/Strassen story, the
    # MathExt import, np.dot-on-lists) survive.
    text = _read_text(_README)
    # The old-doc markers: the v1.2 tag, the factorial/Strassen story, the old
    # MathExt module (import and dotted call, NOT the FastMathExt project name),
    # and np.dot-on-lists timing. None survive the rewrite.
    for marker in (
        "v1.2",
        "factorial",
        "Strassen",
        "import MathExt",
        "MathExt.",
        "np.dot",
    ):
        assert marker not in text, f"old-doc marker {marker!r} survives in README"
    assert "3.0.0" in text  # the current version is stated
    assert "FastMathExt" in text


def test_readme_round_trip_closure():
    # The round-trip closure: every headline number in the README appears in a
    # report.py-rendered string. The README pastes the renderer's tables, so a
    # number that is in the README but NOT producible from JSON is an orphan. Pull
    # the headline values from the committed JSON, assert each is in BOTH the
    # rendered report and the README text.
    report_text = report.render_report()
    readme_text = _read_text(_README)

    matmul_f64 = json.load(
        open(os.path.join(report.RESULTS_DIR, "refbox_matmul_f64.json"))
    )
    scaling = json.load(
        open(os.path.join(report.RESULTS_DIR, "tuning", "scaling_refbox.json"))
    )
    cpu06 = json.load(
        open(os.path.join(report.RESULTS_DIR, "cpu06_f32_refbox.json"))
    )
    gpu = json.load(
        open(os.path.join(report.RESULTS_DIR, "refbox_gpu_matrix.json"))
    )
    fuse_cpu = json.load(
        open(os.path.join(report.RESULTS_DIR, "fuse05_cpu_f32_refbox.json"))
    )
    fuse_gpu = json.load(
        open(os.path.join(report.RESULTS_DIR, "fuse05_gpu_f32_refbox.json"))
    )

    n2048 = next(c for c in matmul_f64["cases"] if c["n"] == 2048)
    headline = [
        f"{n2048['speedup_floor']:.2f}",
        f"{n2048['speedup_vs_numpy']:.2f}",
        f"{scaling['ratio_6_vs_1_floor']:.2f}",
        f"{report._gpu08_ratio(gpu):.2f}",
        f"{fuse_cpu['cpu_cases'][0]['speedup_floor']:.2f}",
        f"{fuse_gpu['gpu_cases'][0]['ratio_vs_numpy_cpu_f32']:.2f}",
    ]
    headline += [f"{c['speedup_vs_numpy']:.2f}" for c in cpu06["cases"]]

    for value in headline:
        assert value in report_text, f"{value} not in rendered report"
        assert value in readme_text, f"{value} not in README (orphan or missing)"


def test_readme_has_required_sections():
    # The README carries the required v3 sections: install for both builds, the
    # quickstart surface, the loss rows, the neutral methodology, and the
    # hardware manifest.
    text = _read_text(_README)
    assert "FME_ENABLE_CUDA=ON" in text  # the CUDA build install
    assert "pip install -e ." in text  # the CPU-only default install
    assert "CUDA Toolkit 12.8" in text  # the CUDA version note
    # The quickstart surface (every public op the plan names).
    for op in (
        "matmul",
        "transpose",
        "fme.sum",
        "fme.mean",
        "axpby",
        "fma3",
        "scaled_relu",
        "to_device",
        "from_device",
        "calibrate",
        "set_backend",
    ):
        assert op in text, f"quickstart missing {op}"
    assert "loses to NumPy" in text  # a loss row is present
    assert "Methodology" in text
    assert "floor" in text  # the floor-statistic note
    assert "Hardware" in text
